//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.StudentAnswers = new HashSet<StudentAnswer>();
            this.TestQuestions = new HashSet<TestQuestion>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Answer1 { get; set; }
        public string Answer2 { get; set; }
        public string Answer3 { get; set; }
        public string Answer4 { get; set; }
        public int CorrectAnswer { get; set; }
        public int QuestionType { get; set; }
        public int Points { get; set; }
    
        public virtual ICollection<StudentAnswer> StudentAnswers { get; set; }
        public virtual ICollection<TestQuestion> TestQuestions { get; set; }
    }
}
