//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.StudentAnswers = new HashSet<StudentAnswer>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int TestId { get; set; }
    
        public virtual ICollection<StudentAnswer> StudentAnswers { get; set; }
        public virtual Test Test { get; set; }
    }
}
